### ISSUE TITLE
Organizing releases and splitting work

### ISSUE THREAD

**Issue by mhdatie** [Redgram/redgram-for-reddit#6]
Hey all, I will be attempting to look at open source builds so that whenever code is committed, we want to make sure no one breaks the build or create a merge conflict. This is bound to happen as more people will be working on this project.

Also, I would like to suggest following this branching model http://nvie.com/posts/a-successful-git-branching-model/. Please go through when you have the time.

We should work in parallel. As soon as you are comfortable with the code, we will start splitting teams and create branches for bug fixes, enhancements and new features. 

This should be a good experience to everyone, and I'm excited about it.

Please, if you run into the app and find issues, create an issue immediately and explain what the problem is, not what the code does, the latter should be explained in the comments as we are debugging the issue. 

Please let me know if you have any suggestions.

**Comment by mhdatie** [comment]
I'm currently looking at Travis CI. I have no experience in it but I'm looking to integrate it with Slack as well. Let me know if you have better suggestions.

If you have experience in Travis, let us know.

**Comment by ScottCooper92** [comment]
Circle CI integrates with Github quite nicely: https://github.com/integrations/circle-ci

**Comment by mhdatie** [comment]
Travis is set up on the dev branch but lint is complaining about Java 8 lambas as I'm using them for RxJava. I tried the workaround suggested in retrolamda repo but with no luck.. So it's a gradle issue

**Comment by williamwebb** [comment]
@MohamadAtieh could you link to the failed builds?

**Comment by mhdatie** [comment]
https://travis-ci.org/Redgram/redgram-for-reddit

You can click on the build tag next to the title in the README file

**Comment by mhdatie** [comment]
Go to the travis.yml file in root and run the script provided there locally on your terminal you will see the exact cause of the fail... It's a lint exception

**Comment by mhdatie** [comment]
I was able to run the build successfully on my local machine. Solved the lambda complaints but not the full lint report. Things like unused parameters or SDK specific methods were reported and they can be found in **Redgram/app/build/outputs/lint-results-debug.html**.

I will commit the changes but Travis will fail since I haven't added the commands to start an adb before running the script. I am currently looking at how to do that locally, with the help of this SO question http://stackoverflow.com/questions/31264136/travis-ci-android-tests-no-connected-devices

**Comment by mhdatie** [comment]
Now that we got the Travis part to work, I'm looking into creating a Slack account and link the builds to it.

**Comment by MohamadAtieh** [comment]
##Invite link to Slack

**Comment by mhdatie** [comment]
## Invite link to slack

https://redgram.slack.com/shared_invite/MzUwNTQzMDYzNDAtMTQ2MDczMDExMC00NWU5MzMyOWRl

Let me know if it's expired to create a new one.
