### ISSUE TITLE
Configuring Travis

### ISSUE THREAD

**Issue by mhdatie** [Redgram/redgram-for-reddit#8]
Linking #6 

I will try running Travis locally tonight to reproduce the errors. The script works if an emulator was open and having modified the `.travis.yml` to initialize an adb `before-script`, the build is still failing. 

I will be looking at https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image 

I wonder if there was a way to see the full logs on Travis

**Comment by mhdatie** [comment]
apparently I could do something like this 

https://groups.google.com/forum/#!topic/travis-ci/Vyiy70Rol6U

**Comment by mhdatie** [comment]
The builds are taking too long and there isn't enough space. I'm not sure whether it's building correctly. I'm looking into removing retroLambda and a last resort to fix the build.

**Comment by williamwebb** [comment]
your problem is your flooding the logs with --debug
`"The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).`

Remove this flag.

Also since you mentioned retrolambda you should should probably be using the 3.3.x beta.

**Comment by mhdatie** [comment]
I figured it's the `--debug` , I will try the beta release then

**Comment by mhdatie** [comment]
Ran it again:  # 35 https://travis-ci.org/Redgram/redgram-for-reddit

Got the following error: 
`:app:compileDebugJavaWithJavac.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found`

Looking at this https://github.com/evant/gradle-retrolambda/issues/23

**Comment by mhdatie** [comment]
got it to work! 

Build time: 5 mins 48.693 secs

I'm not sure whether upgrading retrolambda had any effect. But the current build file works.

Closing the issue..
